### ISSUE TITLE
Output Does Not Conform to JUnit Schema

### ISSUE THREAD

**Issue by tp** [mcollina/xunit-junit#2]
Tried to use this on an Atlassian Bamboo Build Server, but it does not work there.

I tried to validate the output using this schema (the only working one I found so far): https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

This is the errors I get when validating a sample file with the schema:

``` sh
=> xmllint --noout --schema junit.xsd test-results/MyCompany.MyTool.#-blueprint-flux-store-component-›-tests-›-tests-›-\[anonymous\].xml
test-results/MyCompany.MyTool.%23-blueprint-flux-store-component-%E2%80%BA-tests-%E2%80%BA-tests-%E2%80%BA-%5Banonymous%5D.xml:2: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'timestamp' is required but missing.
test-results/MyCompany.MyTool.%23-blueprint-flux-store-component-%E2%80%BA-tests-%E2%80%BA-tests-%E2%80%BA-%5Banonymous%5D.xml:2: element testsuite: Schemas validity error : Element 'testsuite': The attribute 'hostname' is required but missing.
test-results/MyCompany.MyTool.%23-blueprint-flux-store-component-%E2%80%BA-tests-%E2%80%BA-tests-%E2%80%BA-%5Banonymous%5D.xml:4: element testcase: Schemas validity error : Element 'testcase': The attribute 'classname' is required but missing.
test-results/MyCompany.MyTool.#-blueprint-flux-store-component-›-tests-›-tests-›-[anonymous].xml fails to validate
~/Projects/XaaSify/xs-uic
```

Are those fields really required, and could they be added by `xunit-junit`?

**Comment by mcollina** [comment]
The problem is that there is no "official" schema, nor it is versioned.
Send a PR when it's working for you.

Have you tried plain xunit, is it not working either?

On a previous version of junit, `timestamp` was `time`, and those other fields where not needed.

Anyway, have a look at:
https://github.com/mcollina/xunit-junit/blob/master/index.js#L45-L63

**Comment by tp** [comment]
Indeed, feeding the raw xunit file from `tap-xunit` into the Bamboo JUnit plug-in works, so I will be using that one.

Thanks for your help.
